# Generated by Django 3.2.21 on 2023-10-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Produto'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Stationay', 'Stationary'), ('Electronics', 'Eletrônicos'), ('Comida', 'Comida')], max_length=20, null=True),
        ),
    ]
